# Generated by Django 6.0 on 2025-12-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_negocio', models.CharField(default='Meu Negócio', max_length=100)),
                ('whatsapp', models.CharField(help_text='Formato: 55DDDNUMERO (ex: 5511999999999)', max_length=20)),
            ],
        ),
    ]
