# Generated by Django 6.0 on 2025-12-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='nome_negocio',
            field=models.CharField(default='Sistema de Agendamento', max_length=100),
        ),
    ]
