# Generated by Django 6.0 on 2025-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_configuracao_nome_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='mensagem_whatsapp',
            field=models.TextField(default='Olá {nome}, gostaria de confirmar meu agendamento:\nServiço: {servico}\nData: {data}\nHorário: {hora}', help_text='Use as variáveis: {nome}, {servico}, {data}, {hora}'),
        ),
    ]
