# Generated by Django 6.0 on 2025-12-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_configuracao_mensagem_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('abertura', models.TimeField()),
                ('fechamento', models.TimeField()),
                ('intervalo_inicio', models.TimeField(blank=True, null=True)),
                ('intervalo_fim', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('dia_semana',)},
            },
        ),
    ]
